export const Breakfasts = [
	{
		name: 'Омлет с ветчиной и грибами',
		imageUrl: '/assets/images/products/breakfasts/ham_and_mushroom_omelet.avif',
		categoryId: 2,
		price: 195,
		desc: 'Горячий сытный омлет с поджаристой корочкой, ветчина, шампиньоны и моцарелла',
		whProduct: 2,
		details: '1 шт, 110 г',
	},
	{
		name: 'Омлет с пепперони',
		imageUrl: '/assets/images/products/breakfasts/pepperoni_omelet.avif',
		categoryId: 2,
		price: 195,
		desc: 'Сытный и сбалансированный завтрак — омлет с поджаристой корочкой, пикантная пепперони, томаты и моцарелла',
		whProduct: 2,
		details: '1 шт, 110 г',
	},
	{
		name: 'Сырники со сгущенным молоком',
		imageUrl:
			'/assets/images/products/breakfasts/cheesecakes_with_condensed_milk.avif',
		categoryId: 2,
		price: 199,
		desc: 'Нежные сырники, приготовленные в печи, с порционным сгущенным молоком',
		whProduct: 2,
		details: '2 шт, 140 г',
	},
	{
		name: 'Сырники с малиновым вареньем 👶',
		imageUrl:
			'/assets/images/products/breakfasts/cheesecakes_with_raspberry_jam.avif',
		categoryId: 2,
		price: 199,
		desc: 'Любимый десерт многих гостей — румяные сырники из печи с малиновым вареньем. Нежные, в меру сладкие и напоминающие детство',
		whProduct: 2,
		details: '2 шт, 150 г',
	},
	{
		name: 'Сырники',
		imageUrl: '/assets/images/products/breakfasts/cheesecakes.avif',
		categoryId: 2,
		price: 170,
		desc: 'Любимый десерт многих гостей — румяные сырники из печи. Нежные, в меру сладкие и напоминающие детство',
		whProduct: 2,
		details: '2 шт, 130 г',
	},
	{
		name: 'Кофе Американо',
		imageUrl: '/assets/images/products/breakfasts/caffe_americano.avif',
		categoryId: 2,
		price: 139,
		desc: 'Горячий кофе для ценителей чистого вкуса',
		whProduct: 2,
		details: '0.4 л, 380 г',
	},
	{
		name: 'Кофе Капучино',
		imageUrl: '/assets/images/products/breakfasts/caffe_capuccino.avif',
		categoryId: 2,
		price: 179,
		desc: 'Легендарный рецепт кофе: эспрессо, горячее молоко и плотная молочная пенка',
		whProduct: 2,
		details: '0.4 л, 250 г',
	},
	{
		name: 'Кофе Латте',
		imageUrl: '/assets/images/products/breakfasts/caffe_latte.avif',
		categoryId: 2,
		price: 179,
		desc: 'Идеально сбалансированное сочетание кофе, увеличенной порции молока и нежнейшей пенки',
		whProduct: 2,
		details: '0.4 л, 330 г',
	},
]
