export const Coffee = [
	{
		name: 'Айс капучино',
		imageUrl: '/assets/images/products/coffee/ice_cappuccino.avif',
		categoryId: 5,
		price: 179,
		desc: 'Освежающий холодный кофе с порцией эспрессо и пломбиром',
		whProduct: 2,
		details: '0.3 л, 280 г',
	},
	{
		name: 'Карамельный капучино',
		imageUrl: '/assets/images/products/coffee/сoffee_сaramel_сappuccino.avif',
		categoryId: 5,
		price: 179,
		desc: 'Классический капучино с молочной пенкой и карамельным сиропом',
		whProduct: 2,
		details: '0.3 л, 230 г',
	},
	{
		name: 'Кофе Кокосовый латте',
		imageUrl: '/assets/images/products/coffee/coffee_coconut_latte.avif',
		categoryId: 5,
		price: 179,
		desc: 'Горячий латте с кокосовым сиропом',
		whProduct: 2,
		details: '0.3 л, 300 г',
	},
	{
		name: 'Кофе Американо',
		imageUrl: '/assets/images/products/coffee/caffe_americano.avif',
		categoryId: 5,
		price: 139,
		desc: 'Горячий кофе для ценителей чистого вкуса',
		whProduct: 2,
		details: '0.4 л, 380 г',
	},
	{
		name: 'Кофе Латте',
		imageUrl: '/assets/images/products/coffee/caffe_latte.avif',
		categoryId: 5,
		price: 179,
		desc: 'Идеально сбалансированное сочетание кофе, увеличенной порции молока и нежнейшей пенки',
		whProduct: 2,
		details: '0.4 л, 330 г',
	},
	{
		name: 'Кофе Капучино',
		imageUrl: '/assets/images/products/coffee/cappuccino_coffee.avif',
		categoryId: 5,
		price: 179,
		desc: 'Легендарный рецепт кофе: эспрессо, горячее молоко и плотная молочная пенка',
		whProduct: 2,
		details: '0.4 л, 250 г',
	},
	{
		name: 'Кофе Ореховый латте',
		imageUrl: '/assets/images/products/coffee/coffee_hazelnut_latte.avif',
		categoryId: 5,
		price: 179,
		desc: 'Горячий латте с сиропом со вкусом фундука',
		whProduct: 2,
		details: '0.3 л, 300 г',
	},
	{
		name: 'Капучино Яблочный пирог',
		imageUrl: '/assets/images/products/coffee/cappuccino_apple_pie.avif',
		categoryId: 5,
		price: 169,
		desc: 'Классический капучино с молочной пенкой и ярким сиропом — напоминает по вкусу домашнюю шарлотку',
		whProduct: 2,
		details: '0.3 л, 210 г',
	},
]
