export const Desserts = [
	{
		name: 'Карамельный чизкейк',
		imageUrl: '/assets/images/products/desserts/caramel_cheesecake.avif',
		categoryId: 7,
		price: 189,
		desc: 'Сливочный десерт с очень карамельной начинкой, шоколадным печеньем и орехами',
		whProduct: 2,
		details: '1 шт, 100 г',
	},
	{
		name: 'Черничный маффин',
		imageUrl: '/assets/images/products/desserts/blueberry_muffin.avif',
		categoryId: 7,
		price: 119,
		desc: 'Воздушный кекс с ароматной начинкой из натуральной черники',
		whProduct: 2,
		details: '1 шт, 120 г',
	},
	{
		name: 'Тирамису',
		imageUrl: '/assets/images/products/desserts/tiramisu.avif',
		categoryId: 7,
		price: 199,
		desc: 'Многослойный десерт в лучших итальянских традициях: легкий аромат какао, пропитанная кофе бисквитная прослойка и нежный крем',
		whProduct: 2,
		details: '1 шт, 90г',
	},
	{
		name: 'Додобоны',
		imageUrl: '/assets/images/products/desserts/dodobones.avif',
		categoryId: 7,
		price: 130,
		desc: 'Когда сливочное встречается с пряным, получаются горячие булочки с корицей в фирменном пломбирном соусе',
		whProduct: 2,
		details: '8 шт, 120 г',
	},
	{
		name: 'Чизкейк Нью-Йорк',
		imageUrl: '/assets/images/products/desserts/new_york_cheesecake.avif',
		categoryId: 7,
		price: 189,
		desc: 'Нежнейшая сырная основа, тонкий корж песочного теста и никаких добавок. Классика в мире десертов',
		whProduct: 2,
		details: '1 шт, 100 г',
	},
	{
		name: 'Чизкейк Банановый с шоколадным печеньем',
		imageUrl:
			'/assets/images/products/desserts/banana_cheesecake_with_chocolate_chip_cookies.avif',
		categoryId: 7,
		price: 189,
		desc: 'Солнечная версия классического рецепта: нежный чизкейк с бананом и шоколадным печеньем',
		whProduct: 2,
		details: '1 шт, 100 г',
	},
	{
		name: 'Макарон с манго и маракуйей',
		imageUrl: '/assets/images/products/desserts/mango_maracuja_macaroon.avif',
		categoryId: 7,
		price: 169,
		desc: 'Знаменитый французский десерт со вкусом тропических фруктов. Bon appétit!',
		whProduct: 2,
		details: '2 шт, 24 г',
	},
	{
		name: 'Эклеры-мини с заварным кремом',
		imageUrl: '/assets/images/products/desserts/mini_eclairs_with_custard.avif',
		categoryId: 7,
		price: 169,
		desc: 'Три маленьких, но таких милых эклерчика с заварным кремом. Можно поделиться с друзьями',
		whProduct: 2,
		details: '1 шт, 45 г',
	},
	{
		name: 'Шоколадный кукис',
		imageUrl: '/assets/images/products/desserts/chocolate_kookies.avif',
		categoryId: 7,
		price: 115,
		desc: 'Мягкое печенье с кусочками темного шоколада. Идеально сочетается с чаем, кофе или какао',
		whProduct: 2,
		details: '1 шт, 70 г',
	},
	{
		name: 'Фондант',
		imageUrl: '/assets/images/products/desserts/fondant.avif',
		categoryId: 7,
		price: 389,
		desc: 'Французский шоколадный десерт с хрустящей корочкой и жидкой начинкой',
		whProduct: 2,
		details: '2 шт, 160 г',
	},
	{
		name: 'Сорбет Лимонный фреш ',
		imageUrl: '/assets/images/products/desserts/sorbet_lemon_fresh.avif',
		categoryId: 7,
		price: 145,
		desc: 'Цитрусовая свежесть и сладкий вкус с приятной кислинкой',
		whProduct: 2,
		details: '1 шт, 90 г',
	},
	{
		name: 'Сорбет Клубничный гранат',
		imageUrl:
			'/assets/images/products/desserts/strawberry_pomegranate_sorbet.avif',
		categoryId: 7,
		price: 145,
		desc: 'Охлаждающий дуэт сочных ягод и спелых фруктов',
		whProduct: 2,
		details: '1 шт, 90 г',
	},
]
