export const Drinks = [
	{
		name: 'Добрый Кола',
		imageUrl: '/assets/images/products/drinks/good_cola.avif',
		categoryId: 6,
		price: 135,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Добрый Кола без сахара',
		imageUrl: '/assets/images/products/drinks/good_coke_no_sugar.avif',
		categoryId: 6,
		price: 135,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Добрый Апельсин',
		imageUrl: '/assets/images/products/drinks/good_orange.avif',
		categoryId: 6,
		price: 135,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Добрый Манго-Маракуйя ',
		imageUrl: '/assets/images/products/drinks/good_mango_maracuja.avif',
		categoryId: 6,
		price: 135,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Rich Tea Черный с лимоном',
		imageUrl: '/assets/images/products/drinks/rich_tea_black_with_lemon.avif',
		categoryId: 6,
		price: 139,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Rich Tea Зеленый',
		imageUrl: '/assets/images/products/drinks/rich_tea_green.avif',
		categoryId: 6,
		price: 139,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Напиток сокосодержащий Pulpy Апельсин',
		imageUrl: '/assets/images/products/drinks/pulpy_orange_juice_drink.avif',
		categoryId: 6,
		price: 149,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Вода BonaAqua негазированная',
		imageUrl: '/assets/images/products/drinks/bonaAqua_still_water.avif',
		categoryId: 6,
		price: 100,
		desc: '',
		whProduct: 2,
		details: '0.5 л',
	},
	{
		name: 'Апельсиновый нектар Rich ',
		imageUrl: '/assets/images/products/drinks/orange_nectar_rich.avif',
		categoryId: 6,
		price: 249,
		desc: '',
		whProduct: 2,
		details: '1 л',
	},
	{
		name: 'Яблочный сок Rich',
		imageUrl: '/assets/images/products/drinks/rich_apple_juice.avif',
		categoryId: 6,
		price: 249,
		desc: '',
		whProduct: 2,
		details: '1 л',
	},
	{
		name: 'Вишневый нектар Rich',
		imageUrl: '/assets/images/products/drinks/rich_cherry_nectar.avif',
		categoryId: 6,
		price: 249,
		desc: '',
		whProduct: 2,
		details: '1 л',
	},
	{
		name: 'Нектар Добрый мультифрукт',
		imageUrl: '/assets/images/products/drinks/nectar_dobryi_multifruit.avif',
		categoryId: 6,
		price: 249,
		desc: '',
		whProduct: 2,
		details: '1 л',
	},
	{
		name: 'Нектар Добрый апельсин',
		imageUrl: '/assets/images/products/drinks/dobryi_orange_nectar.avif',
		categoryId: 6,
		price: 249,
		desc: 'Незабываемый бодрящий вкус с освежающей кислинкой - результат искусного сочетания отборных сортов спелых и сочных апельсинов. Вкусный и полезный освежающий напиток.',
		whProduct: 2,
		details: '1 л',
	},
	{
		name: 'Морс Клюква 👶',
		imageUrl: '/assets/images/products/drinks/cranberry_morsels.avif',
		categoryId: 6,
		price: 155,
		desc: 'Фирменный ягодный морс из натуральной клюквы с терпким послевкусием Дизайн товара может отличаться',
		whProduct: 2,
		details: '0.45 л',
	},
	{
		name: 'Морс Черная смородина 👶',
		imageUrl: '/assets/images/products/drinks/blackcurrant_morsels.avif',
		categoryId: 6,
		price: 155,
		desc: 'Фирменный ягодный морс из натуральной душистой черной смородины Дизайн товара может отличаться',
		whProduct: 2,
		details: '0.45 л',
	},
	{
		name: 'Морс Вишня 👶',
		imageUrl: '/assets/images/products/drinks/mors_cherry.avif',
		categoryId: 6,
		price: 155,
		desc: 'Фирменный ягодный морс из натуральной спелой вишни. В меру сладкий и с приятной кислинкой Дизайн товара может отличаться',
		whProduct: 2,
		details: '0.45 л',
	},
]
